language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PINS="mirage-clock:. mirage-clock-lwt:. mirage-clock-unix:. mirage-clock-freestanding:."
matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.04 PACKAGE="mirage-clock-freestanding"
  - os: linux
    env: OCAML_VERSION=4.06 PACKAGE="mirage-clock-unix"
  - os: osx
    env: OCAML_VERSION=4.04 PACKAGE="mirage-clock-unix"
